name: Healthy Brain
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35745950508862734
title: Neurofeedback You Can Trust
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03010c'
    - '#80c1c8'
    - '#b9e7d7'
    - '#428954'
    - '#174c78'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
